In [1]:
### import packages

## lets basic import packages

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
 
from sklearn.utils import shuffle    
# from pandas_profiling import ProfileReport

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Perceptron
from sklearn.linear_model import RidgeClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.svm import SVC
from sklearn.svm import LinearSVC

from sklearn.neighbors import KNeighborsRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split


from sklearn import metrics
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import plot_roc_curve
from sklearn.metrics import precision_score
from sklearn.metrics import roc_curve
from sklearn.metrics import recall_score

In [2]:

#importing the dataset

data= pd.read_csv('dataset.csv')
data= shuffle(data, random_state = 42)
data

Disease        Symptom_1            Symptom_2  \
373                  Acne        skin_rash           blackheads   
4916                 Acne        skin_rash   pus_filled_pimples   
1550      Hyperthyroidism          fatigue          mood_swings   
3081                 AIDS   muscle_wasting    patches_in_throat   
3857  Chronic cholestasis          itching             vomiting   
...                   ...              ...                  ...   
4426            Psoriasis        skin_rash           joint_pain   
466   Peptic ulcer diseae         vomiting          indigestion   
3092               Dengue        skin_rash               chills   
3772     Fungal infection          itching            skin_rash   
860         Drug Reaction          itching            skin_rash   

                  Symptom_3                Symptom_4              Symptom_5  \
373                scurring                      NaN                    NaN   
4916             blackheads                 scurring                    NaN   
1550            weight_loss             restlessness               sweating   
3081             high_fever   extra_marital_contacts                    NaN   
3857         yellowish_skin                   nausea       loss_of_appetite   
...                     ...                      ...                    ...   
4426           skin_peeling      silver_like_dusting   small_dents_in_nails   
466        loss_of_appetite           abdominal_pain       internal_itching   
3092             joint_pain                 vomiting                fatigue   
3772   nodal_skin_eruptions      dischromic _patches                    NaN   
860            stomach_pain      burning_micturition    spotting_ urination   

                Symptom_6           Symptom_7          Symptom_8  \
373                   NaN                 NaN                NaN   
4916                  NaN                 NaN                NaN   
1550            diarrhoea     fast_heart_rate   excessive_hunger   
3081                  NaN                 NaN                NaN   
3857       abdominal_pain   yellowing_of_eyes                NaN   
...                   ...                 ...                ...   
4426   inflammatory_nails                 NaN                NaN   
466                   NaN                 NaN                NaN   
3092           high_fever            headache             nausea   
3772                  NaN                 NaN                NaN   
860                   NaN                 NaN                NaN   

              Symptom_9             Symptom_10              Symptom_11  \
373                 NaN                    NaN                     NaN   
4916                NaN                    NaN                     NaN   
1550    muscle_weakness           irritability   abnormal_menstruation   
3081                NaN                    NaN                     NaN   
3857                NaN                    NaN                     NaN   
...                 ...                    ...                     ...   
4426                NaN                    NaN                     NaN   
466                 NaN                    NaN                     NaN   
3092   loss_of_appetite   pain_behind_the_eyes               back_pain   
3772                NaN                    NaN                     NaN   
860                 NaN                    NaN                     NaN   

     Symptom_12    Symptom_13            Symptom_14 Symptom_15 Symptom_16  \
373         NaN           NaN                   NaN        NaN        NaN   
4916        NaN           NaN                   NaN        NaN        NaN   
1550        NaN           NaN                   NaN        NaN        NaN   
3081        NaN           NaN                   NaN        NaN        NaN   
3857        NaN           NaN                   NaN        NaN        NaN   
...         ...           ...                   ...        ...        ...   
4426        NaN    

In [3]:
#remove ('_') underscore in the text

for col in data.columns:
    data[col] = data[col].str.replace('_', ' ')
    
data.head()

Disease        Symptom_1            Symptom_2  \
373                  Acne        skin rash           blackheads   
4916                 Acne        skin rash   pus filled pimples   
1550      Hyperthyroidism          fatigue          mood swings   
3081                 AIDS   muscle wasting    patches in throat   
3857  Chronic cholestasis          itching             vomiting   

            Symptom_3                Symptom_4          Symptom_5  \
373          scurring                      NaN                NaN   
4916       blackheads                 scurring                NaN   
1550      weight loss             restlessness           sweating   
3081       high fever   extra marital contacts                NaN   
3857   yellowish skin                   nausea   loss of appetite   

            Symptom_6           Symptom_7          Symptom_8  \
373               NaN                 NaN                NaN   
4916              NaN                 NaN                NaN   
1550        diarrhoea     fast heart rate   excessive hunger   
3081              NaN                 NaN                NaN   
3857   abdominal pain   yellowing of eyes                NaN   

             Symptom_9     Symptom_10              Symptom_11 Symptom_12  \
373                NaN            NaN                     NaN        NaN   
4916               NaN            NaN                     NaN        NaN   
1550   muscle weakness   irritability   abnormal menstruation        NaN   
3081               NaN            NaN                     NaN        NaN   
3857               NaN            NaN                     NaN        NaN   

     Symptom_13 Symptom_14 Symptom_15 Symptom_16 Symptom_17  
373         NaN        NaN        NaN        NaN        NaN  
4916        NaN        NaN        NaN        NaN        NaN  
1550        NaN        NaN        NaN        NaN        NaN  
3081        NaN        NaN        NaN        NaN        NaN  
3857        NaN        NaN        NaN        NaN        NaN

In [9]:

#data preprocessing

# check for null values from the dataset

data.isna().sum()

Disease          0
Symptom_1        0
Symptom_2        0
Symptom_3        0
Symptom_4      348
Symptom_5     1206
Symptom_6     1986
Symptom_7     2652
Symptom_8     2976
Symptom_9     3228
Symptom_10    3408
Symptom_11    3726
Symptom_12    4176
Symptom_13    4416
Symptom_14    4614
Symptom_15    4680
Symptom_16    4728
Symptom_17    4848
dtype: int64

In [10]:

#clean the null values

data=data.fillna(0)
data.isna().sum()


Disease       0
Symptom_1     0
Symptom_2     0
Symptom_3     0
Symptom_4     0
Symptom_5     0
Symptom_6     0
Symptom_7     0
Symptom_8     0
Symptom_9     0
Symptom_10    0
Symptom_11    0
Symptom_12    0
Symptom_13    0
Symptom_14    0
Symptom_15    0
Symptom_16    0
Symptom_17    0
dtype: int64

In [11]:

# charactieristics of data

data.describe()

Disease  Symptom_1  Symptom_2 Symptom_3    Symptom_4  Symptom_5  \
count     4920       4920       4920      4920         4920       4920   
unique      41         34         48        54           51         39   
top       Acne   vomiting   vomiting   fatigue   high fever          0   
freq       120        822        870       726          378       1206   

        Symptom_6  Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  \
count        4920       4920       4920       4920        4920        4920   
unique         33         27         22         23          22          19   
top             0          0          0          0           0           0   
freq         1986       2652       2976       3228        3408        3726   

        Symptom_12  Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
count         4920        4920        4920        4920        4920        4920  
unique          12           9           5           4           4           2  
top              0           0           0           0           0           0  
freq          4176        4416        4614        4680        4728        4848

In [12]:
# Data Types

data.dtypes

Disease       object
Symptom_1     object
Symptom_2     object
Symptom_3     object
Symptom_4     object
Symptom_5     object
Symptom_6     object
Symptom_7     object
Symptom_8     object
Symptom_9     object
Symptom_10    object
Symptom_11    object
Symptom_12    object
Symptom_13    object
Symptom_14    object
Symptom_15    object
Symptom_16    object
Symptom_17    object
dtype: object

In [13]:
cols= data.columns

data1= data[cols].values.flatten()

reshaped = pd.Series(data1)
reshaped = reshaped.str.strip()
reshaped = reshaped.values.reshape(data.shape)

data = pd.DataFrame(reshaped, columns = data.columns)
data.head()


Disease       Symptom_1           Symptom_2       Symptom_3  \
0                 Acne       skin rash          blackheads        scurring   
1                 Acne       skin rash  pus filled pimples      blackheads   
2      Hyperthyroidism         fatigue         mood swings     weight loss   
3                 AIDS  muscle wasting   patches in throat      high fever   
4  Chronic cholestasis         itching            vomiting  yellowish skin   

                Symptom_4         Symptom_5       Symptom_6  \
0                     NaN               NaN             NaN   
1                scurring               NaN             NaN   
2            restlessness          sweating       diarrhoea   
3  extra marital contacts               NaN             NaN   
4                  nausea  loss of appetite  abdominal pain   

           Symptom_7         Symptom_8        Symptom_9    Symptom_10  \
0                NaN               NaN              NaN           NaN   
1                NaN               NaN              NaN           NaN   
2    fast heart rate  excessive hunger  muscle weakness  irritability   
3                NaN               NaN              NaN           NaN   
4  yellowing of eyes               NaN              NaN           NaN   

              Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0                    NaN        NaN        NaN        NaN        NaN   
1                    NaN        NaN        NaN        NaN        NaN   
2  abnormal menstruation        NaN        NaN        NaN        NaN   
3                    NaN        NaN        NaN        NaN        NaN   
4                    NaN        NaN        NaN        NaN        NaN   

  Symptom_16 Symptom_17  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [14]:
## lets explore symptom severity

Symptom_severity = pd.read_csv('Symptom-severity.csv')
Symptom_severity.shape

(133, 2)

In [15]:
Symptom_severity['Symptom'] =Symptom_severity['Symptom'].str.replace('_',' ')
Symptom_severity.head(10)

Symptom  weight
0               itching       1
1             skin rash       3
2  nodal skin eruptions       4
3   continuous sneezing       4
4             shivering       5
5                chills       3
6            joint pain       3
7          stomach pain       5
8               acidity       3
9      ulcers on tongue       4

In [16]:
## overall list

Symptom_severity['Symptom'].unique()

array(['itching', 'skin rash', 'nodal skin eruptions',
       'continuous sneezing', 'shivering', 'chills', 'joint pain',
       'stomach pain', 'acidity', 'ulcers on tongue', 'muscle wasting',
       'vomiting', 'burning micturition', 'spotting urination', 'fatigue',
       'weight gain', 'anxiety', 'cold hands and feets', 'mood swings',
       'weight loss', 'restlessness', 'lethargy', 'patches in throat',
       'irregular sugar level', 'cough', 'high fever', 'sunken eyes',
       'breathlessness', 'sweating', 'dehydration', 'indigestion',
       'headache', 'yellowish skin', 'dark urine', 'nausea',
       'loss of appetite', 'pain behind the eyes', 'back pain',
       'constipation', 'abdominal pain', 'diarrhoea', 'mild fever',
       'yellow urine', 'yellowing of eyes', 'acute liver failure',
       'fluid overload', 'swelling of stomach', 'swelled lymph nodes',
       'malaise', 'blurred and distorted vision', 'phlegm',
       'throat irritation', 'redness of eyes', 'sinus pressu

In [ ]:
# lets encode sysptoms in the data

vals = data.values
symptoms =Symptom_severity['Symptom'].unique()

for i in range(len(symptoms)):
    vals[vals == symptoms[i]] = Symptom_severity[Symptom_severity['Symptom'] == symptoms[i]]['weight'].values[0]


In [ ]:
data_processed = pd.DataFrame(vals, columns=cols)
data_processed=data_processed.fillna(0)
data_processed.head()

In [ ]:
## assign symptoms with no rank to zero

data_processed = data_processed.replace('dischromic  patches', 0)
data_processed = data_processed.replace('spotting  urination', 0)
data_processed = data_processed.replace('foul smell of urine', 0)
le=preprocessing.LabelEncoder()
data_processed['Disease']=le.fit_transform(data_processed['Disease'])
data['Disease']=le.fit_transform(data['Disease'])
data_processed.head()

In [3]:
#extracting features and target variables

x= data_processed.iloc[:,1:].values
y=data['Disease'].values

NameError: name 'data_processed' is not defined

In [22]:

y

array([ 2,  2, 24, ..., 11, 15, 14], dtype=int64)

In [23]:
# split train and test data

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2, random_state=42)


In [38]:

    x

array([[3, 2, 2, ..., 0, 0, 0],
       [3, 2, 2, ..., 0, 0, 0],
       [4, 3, 3, ..., 0, 0, 0],
       ...,
       [3, 3, 3, ..., 0, 0, 0],
       [1, 3, 4, ..., 0, 0, 0],
       [1, 3, 5, ..., 0, 0, 0]], dtype=int64)

In [98]:
print(xtrain[0])
print(xtrain[1])

[6 4 0 6 0 0 0 0 0 0 0 0 0 0 0 0 0]
[3 5 3 5 4 4 3 2 3 0 0 0 0 0 0 0 0]


In [34]:
# Machine Learning Algorithms

# 1)SVR

from sklearn.svm import SVC
model=SVC(kernel='linear')
model.fit(xtrain,ytrain)


SVC(kernel='linear')

In [35]:
result=model.predict(xtest)
result

array([30, 33, 15, 25, 19, 19, 34, 28,  1,  3,  7, 31,  7, 29, 16, 15, 26,
       25,  7, 22,  5, 10,  7, 23, 22, 21, 15,  6,  7, 24, 40,  4,  7, 38,
       37,  2, 28, 36,  5, 11, 36,  8, 23, 30, 21,  5,  5, 26,  4, 11, 16,
       37, 25, 22, 15, 14, 23,  1, 28, 10, 23, 14, 13, 38, 29,  7, 33, 36,
       17, 36, 19, 39,  6,  5, 36, 24, 34,  3,  1, 23,  6,  7, 16, 22, 14,
       35, 36, 33, 27,  7,  8, 26, 22,  2, 21, 11, 31, 19,  1,  8, 23, 36,
       38,  4, 23, 13, 21, 13, 32,  6, 17, 25, 12,  2,  2,  5, 24, 40, 17,
       29, 40, 23, 10, 37, 23, 26,  5, 34,  5, 13, 33, 24, 15, 39, 22, 33,
       19, 31,  2, 40, 20, 12,  5,  0, 26, 13, 14, 33, 34, 39, 26, 28, 19,
       21, 10,  7,  0,  2, 11, 20,  6, 37, 36, 20, 35, 11, 21, 33, 21, 34,
       31, 17, 24, 12,  3, 20,  2, 37, 12, 21,  9, 26, 21, 19, 17, 37, 24,
       28, 14, 20, 16, 30,  3, 38, 13,  3, 33, 31, 23, 25, 27, 39, 11,  0,
       30,  8, 18,  3, 21, 17, 25, 34, 40, 18, 17,  3, 32, 14, 39, 20,  8,
       33, 32, 11, 17, 20

In [36]:
model.score(xtrain,ytrain)

0.9842479674796748

In [37]:
model.score(xtest,ytest)

0.983739837398374

In [43]:
newresult=model.predict([[1,5,3,5,4,4,4,4,4,4,5,5,0,0,0,0,0]])
print(newresult)

[11]


In [40]:
print(classification_report(ytest,predict))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        18
           1       0.09      0.40      0.14        20
           2       0.00      0.00      0.00        32
           3       0.07      1.00      0.13        29
           4       0.00      0.00      0.00        19
           5       0.00      0.00      0.00        31
           6       0.00      0.00      0.00        28
           7       0.00      0.00      0.00        30
           8       0.00      0.00      0.00        27
           9       0.00      0.00      0.00        19
          10       0.00      0.00      0.00        25
          11       0.00      0.00      0.00        22
          12       0.00      0.00      0.00        23
          13       0.08      1.00      0.14        30
          14       0.00      0.00      0.00        21
          15       0.00      0.00      0.00        25
          16       0.00      0.00      0.00        24
          17       0.00    

C:\Users\ADMIN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ADMIN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [49]:
print(confusion_matrix(ytest,predict))

[[ 0  0  0 ...  0  0  0]
 [ 0  8  0 ...  0  0  0]
 [ 0 14  0 ...  0  0  0]
 ...
 [ 0  7  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [52]:
# KNN

model=KNeighborsRegressor(n_neighbors=4)
model

KNeighborsRegressor(n_neighbors=4)

In [54]:
model.fit(xtrain,ytrain)
result=model.predict(xtest)
model.score(xtrain,ytrain)

0.9910847995195144

In [55]:

model.score(xtest,ytest)

0.9929126281077315

In [2]:
# GradientBoostingClassifier
from sklearn.ensemble import GradientBoostingClassifier
model=GradientBoostingClassifier(learning_rate=0.1)
model.fit(xtrain,ytrain)
newdata=model.predict(xtest)

NameError: name 'xtrain' is not defined

In [ ]:
model.score(xtrain,ytrain)

In [ ]:
model.score(xtest,ytest)

In [ ]:
# decision tree 
# Random forest
# Naives Bayes
# KNearest neighbor